name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull Latest Docker Images
        run: |
          docker-compose pull

      - name: Stop Specific Containers
        run: |
          # Define the service to update (pass this via secrets or environment variables)
          SERVICE_TO_UPDATE=${{ secrets.UPDATE_SERVICE }}

          if [ -z "$SERVICE_TO_UPDATE" ]; then
            echo "No specific service specified. Skipping container stop."
          else
            echo "Stopping only the specified service(s): $SERVICE_TO_UPDATE"
            for service in $SERVICE_TO_UPDATE; do
              echo "Stopping container for service: $service"
              docker-compose stop $service || echo "Service $service is not running."
            done
          fi

      - name: Start Specific Containers
        run: |
          # Define the service to update (pass this via secrets or environment variables)
          SERVICE_TO_UPDATE=${{ secrets.UPDATE_SERVICE }}

          if [ -z "$SERVICE_TO_UPDATE" ]; then
            echo "No specific service specified. Starting all services..."
            docker-compose up -d
          else
            echo "Starting the specified service(s): $SERVICE_TO_UPDATE"
            docker-compose up -d $SERVICE_TO_UPDATE
          fi
