version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      retries: 5

  node:
    image: rajendra0968/mysql-express:latest
    container_name: node_app
    working_dir: /usr/src/app
    networks:
      - app_network
    ports:
      - "5000:5000"
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_healthy
    # env_file:
    #   - .env
    environment:
      DB_HOST: mysqldb
      NODE_ENV: development
      PORT: 5000

  redis:
    image: redis:latest
    container_name: redis_container
    command: >
      redis-server
      ${REDIS_USE_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - 6379
    # env_file:
    #   - .env
    environment:
       REDIS_HOST: redis_host
       REDIS_PORT: 6379
       REDIS_USE_PASSWORD: mysecretpassword
       REDIS_PASSWORD: your_password 
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: db_user
      PMA_PASSWORD: db_pass
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - app_network      

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
