version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      retries: 5

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /usr/src/app
    networks:
      - app_network
    ports:
      - "5000:5000"
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: mysqldb

  redis:
    image: redis:latest
    container_name: redis_container
    command: >
      redis-server
      ${REDIS_USE_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - 6379
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 10s
      retries: 5

networks:
  app_network:
    driver: bridge
