name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Start Services
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Wait for Services to be Healthy
      run: |
        sleep 30  # Adjust the duration based on service startup time

    - name: Run Application Tests
      run: |
        # Replace with actual tests or commands to verify services
        curl -f http://localhost:5000 || exit 1

    - name: Shut Down Services
      if: always()
      run: docker-compose down
