name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Start Services
      run: |
        docker-compose --env-file .env -f docker-compose.yml up --build -d

    - name: Wait for Services to be Healthy
      run: |
        echo "Waiting for services to be healthy..."
        sleep 60

    - name: Verify Services
      run: |
        docker ps
        curl -f http://localhost:5000 || exit 1

    - name: Shut Down Services
      if: always()
      run: docker-compose down
