name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Start Services
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Wait for MySQL and Redis Services
      run: |
        echo "Waiting for services to be healthy..."
        sleep 60  # Adjust this based on your healthcheck intervals

    - name: Verify MySQL Service
      run: |
        docker exec mysql_container mysqladmin ping -h localhost -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }}

    - name: Verify Redis Service
      run: |
        docker exec redis_container redis-cli -a ${REDIS_PASSWORD:-""} ping

    - name: Run Node Application Tests
      run: |
        curl -f http://localhost:5000 || exit 1

    - name: Shut Down Services
      if: always()
      run: docker-compose down
