name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Pull Latest Docker Images
      run: |
        docker-compose pull

    - name: Stop and Remove Old Containers
      run: |
        docker-compose down

    - name: Start New Containers
      run: |
        docker-compose up -d
